# Git - latest version, override mac OS pre-install
brew 'git'
brew 'git-lfs'

# Swift, Cocoa, Xcode etc.
brew 'mergepbx'

brew 'fish'
brew 'gh'
brew 'fnm'
brew 'pinentry'
brew 'pinentry-mac'
brew 'pyenv'
brew 'starship'
brew 'stern'

# Apps
cask 'appcleaner'
cask 'arc'
cask 'autodesk-fusion'
cask 'bambu-studio'
cask 'bettertouchtool'
cask 'caffeine'
cask 'charles'
cask 'daisydisk'
cask 'github'
cask 'google-cloud-sdk'
cask 'gpg-suite-no-mail'
cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'notion'
cask 'obsidian'
cask 'paw'
cask 'postico'
cask 'provisioning'
cask 'rocket'
cask 'signal'
cask 'spotmenu'
cask 'telegram'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'

# Fonts
tap 'homebrew/cask-fonts'
cask 'font-hack-nerd-font'
